"""adiciona snapshot do endereco ao pedido

Revision ID: 219ffe4bdfea
Revises: e1f7771dade9
Create Date: 2026-09-19 23:08:40.605535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219ffe4bdfea'
down_revision: Union[str, Sequence[str], None] = 'e1f7771dade9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_zip_code', sa.String(length=9), nullable=True))
    op.add_column('orders', sa.Column('delivery_street', sa.String(length=150), nullable=True))
    op.add_column('orders', sa.Column('delivery_number', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_complement', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_reference', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_reference')
    op.drop_column('orders', 'delivery_complement')
    op.drop_column('orders', 'delivery_number')
    op.drop_column('orders', 'delivery_street')
    op.drop_column('orders', 'delivery_zip_code')
    # ### end Alembic commands ###
