"""cria sabores da pizza no item do pedido

Revision ID: 5cf7615111a6
Revises: 7284f249f08e
Create Date: 2026-09-19 23:42:02.465395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf7615111a6'
down_revision: Union[str, Sequence[str], None] = '7284f249f08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_pizza_flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('flavor_id', sa.Integer(), nullable=False),
    sa.Column('flavor_name', sa.String(length=120), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('fraction', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.CheckConstraint('fraction IN (0.5, 1.0)', name='ck_order_item_pizza_flavors_fraction_valid'),
    sa.CheckConstraint('slot IN (1, 2)', name='ck_order_item_pizza_flavors_slot_valid'),
    sa.ForeignKeyConstraint(['flavor_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', 'slot', name='uq_order_item_pizza_flavors_item_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_pizza_flavors')
    # ### end Alembic commands ###
