"""cria detalhes da pizza no item do pedido

Revision ID: 7284f249f08e
Revises: ca4effbf5c0b
Create Date: 2026-09-19 23:39:29.139461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7284f249f08e'
down_revision: Union[str, Sequence[str], None] = 'ca4effbf5c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_pizza_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('crust_id', sa.Integer(), nullable=True),
    sa.Column('crust_name', sa.String(length=80), nullable=True),
    sa.Column('crust_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('crust_price >= 0', name='ck_order_item_pizza_details_crust_price_non_negative'),
    sa.ForeignKeyConstraint(['crust_id'], ['crusts.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', name='uq_order_item_pizza_details_order_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_pizza_details')
    # ### end Alembic commands ###
