"""cria tabela business_hours

Revision ID: 7f36c7edff3b
Revises: 94fdbbd5d559
Create Date: 2026-09-20 00:37:08.002349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f36c7edff3b'
down_revision: Union[str, Sequence[str], None] = '94fdbbd5d559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_business_hours_day_of_week_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week', name='uq_business_hours_day_of_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_hours')
    # ### end Alembic commands ###
