"""adiciona bairro de entrega ao pedido

Revision ID: 8489db591a23
Revises: 658104fa26b2
Create Date: 2026-09-19 14:25:05.969627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8489db591a23'
down_revision: Union[str, Sequence[str], None] = '658104fa26b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_neighborhood', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_neighborhood')
    # ### end Alembic commands ###
