"""cria tabela crust prices

Revision ID: 92c88c92e110
Revises: 3c7f3e23de7c
Create Date: 2026-09-19 23:27:30.190937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c88c92e110'
down_revision: Union[str, Sequence[str], None] = '3c7f3e23de7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crust_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crust_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=1), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("size IN ('P', 'M', 'G')", name='ck_crust_prices_size_valid'),
    sa.CheckConstraint('price >= 0', name='ck_crust_prices_price_non_negative'),
    sa.ForeignKeyConstraint(['crust_id'], ['crusts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crust_prices')
    # ### end Alembic commands ###
