"""cria tabela delivery_zones

Revision ID: 94fdbbd5d559
Revises: d3fffb403f67
Create Date: 2026-09-20 00:23:45.527301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fdbbd5d559'
down_revision: Union[str, Sequence[str], None] = 'd3fffb403f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neighborhood', sa.String(length=80), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('fee >= 0', name='ck_delivery_zones_fee_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neighborhood', name='uq_delivery_zones_neighborhood')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
