"""adiciona unicidade ao preco da borda

Revision ID: ca4effbf5c0b
Revises: 92c88c92e110
Create Date: 2026-09-19 23:33:26.861051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4effbf5c0b'
down_revision: Union[str, Sequence[str], None] = '92c88c92e110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_crust_prices_crust_size', 'crust_prices', ['crust_id', 'size'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_crust_prices_crust_size', 'crust_prices', type_='unique')
    # ### end Alembic commands ###
