"""cria tabela payments

Revision ID: d3fffb403f67
Revises: b55653ca29e0
Create Date: 2026-09-19 23:58:33.840286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3fffb403f67'
down_revision: Union[str, Sequence[str], None] = 'b55653ca29e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change_for', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pix_token', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('PIX_DEMO', 'CREDIT_ON_DELIVERY', 'DEBIT_ON_DELIVERY', 'CASH')", name='ck_payments_method_valid'),
    sa.CheckConstraint("status IN ('PENDING', 'PAID', 'EXPIRED', 'CANCELLED')", name='ck_payments_status_valid'),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount_non_negative'),
    sa.CheckConstraint('change_for IS NULL OR change_for > amount', name='ck_payments_change_for_valid'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pix_token', name='uq_payments_pix_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
